spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liefallow?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://120.27.245.202:3306/liefallow?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false

  mvc:
    static-path-pattern: /static/**

file:
  path: file/**
  address: /resources/static/uploadFile

